### ISSUE TITLE
'Maybe' generation inconsistencies

### ISSUE THREAD

**Issue by ronanyeah** [wolfadex/elm-open-api-cli#163]
From this component:
```json
  "components": {
    "schemas": {
      "StatsData": {
        "type": "object",
        "properties": {
          "data1": {
            "oneOf": [
              { "type": "null" },
              { "$ref": "#/components/schemas/Data1" }
            ]
          },
          "value1": { "type": ["string", "null"] }
        }
      }
    }
  }
```

I would expect to get:
```elm
type alias StatsData =
    { data1 : Maybe Data1
    , value1 : Maybe String
    }
```

However this is the result:
```elm
type alias StatsData =
    { data1 : Maybe Empty___Or_Data1
    , value1 : Maybe (OpenApi.Common.Nullable String)
    }


type Empty___Or_Data1
    = Empty___Or_Data1__Empty__ ()
    | Empty___Or_Data1__Data1 Data1
```

[Full example](https://github.com/ronanyeah/openapi-rust-elm)

**Comment by wolfadex** [comment]
Given the schema, `value1 : Maybe (OpenApi.Common.Nullable String)` makes sense I think. It doesn't have `"required": true` which is why it's a `Maybe`, and it's also nullable which is why it's a `OpenApi.Common.Nullable`. There's been discussion before about this being a little odd but no definite conclusion.

We have to solve for
- a value being present or absent
- a present value being null or not (when nullable)

We could had
```elm
type Value a
    = Absent
    | Null
    | Present a
```
But that doesn't work well with a value that is non-nullable, or one that is always required & nullable.
We could also do
```elm
type Optional a
    = Absent
    | Present a

type Nullable a
    = Null
    | NonNull a
```
And maybe that'd be a little more clear? But `Maybe` feels really similar to `Optional`. `Maybe also feels really similar to `Nullable` but `Nothing` and `Null` have very different meanings IMO.

---

I agree that `data1 : Maybe Empty___Or_Data1` is a little odd. I think to make it match `value1` we'd need to have some special checking for `oneOf` to see if 1 of the values is specifically `{ "type": "null" }`. Not sure if this is a good idea or not., but it seems maybe reasonable.

**Comment by ronanyeah** [comment]
After this [PR](https://github.com/wolfadex/elm-open-api-cli/pull/166), and if I add `required` to the fields, this is the result, which I think is sufficient for now:

```elm
type alias StatsData =
    { data1 : OpenApi.Common.Nullable Data1
    , value1 : OpenApi.Common.Nullable String
    }
```
